version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passowrd

  my-test-app:
    image: my-test-app
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb/myapp
    command: yarn test
    depends_on:
      - mongodb